use ratatui::style::Color;

/// Enumeration of supported AI model providers and platforms.
///
/// # Doc aliases
///
/// `AI provider`, `model provider`, `LLM provider`
///
/// Each variant has an associated brand colour ([`Provider::color`]) and
/// display name ([`Provider::name`]).
///
/// # Example
///
/// ```rust
/// use unit_ui::theme::providers::Provider;
/// let color = Provider::Anthropic.color();
/// let name = Provider::Anthropic.name();
/// ```
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Provider {
    OpenAI,
    Anthropic,
    Google,
    Meta,
    Mistral,
    DeepSeek,
    Cohere,
    Ai21,
    Xai,
    Stability,
    Replicate,
    HuggingFace,
    Together,
    Fireworks,
    Groq,
    DeepInfra,
    Perplexity,
    Sambanova,
    Novita,
    SiliconFlow,
    Hyperbolic,
    Lepton,
    Featherless,
    Nebius,
    Korbit,
    Writer,
    Abacus,
    Cerebras,
    Alibaba,
    Baidu,
    Tencent,
    ByteDance,
    Zhipu,
    Oneworld,
    Moonshot,
    Minimax,
    Baichuan,
    StepFun,
    SenseTime,
    Huawei,
    Lingyiwanwu,
    Infinigence,
    Azure,
    Aws,
    Gcp,
    Ibm,
    Oracle,
    Sap,
    Nvidia,
    Cloudflare,
    OpenRouter,
    Portkey,
    Helicone,
    LangChain,
    LlamaIndex,
    Vercel,
    Modal,
    Databricks,
    Ollama,
    LocalAI,
    Vllm,
    Tabby,
    Gpt4All,
    Pinecone,
    Weaviate,
    Chroma,
    Milvus,
    Qdrant,
    Supabase,
    MotherDuck,
    Flyio,
    Railway,
    Render,
    Scale,
    Midjourney,
    Runway,
    Pika,
    ElevenLabs,
    Synthesia,
    Goose,
    Mosaicml,
}

impl Provider {
    /// Returns the brand colour for this provider.
    pub fn color(self) -> Color {
        match self {
            Self::OpenAI => Color::Rgb(16, 163, 127),
            Self::Anthropic => Color::Rgb(217, 119, 87),
            Self::Google => Color::Rgb(66, 133, 244),
            Self::Meta => Color::Rgb(8, 102, 255),
            Self::Mistral => Color::Rgb(255, 106, 0),
            Self::DeepSeek => Color::Rgb(79, 107, 237),
            Self::Cohere => Color::Rgb(57, 89, 77),
            Self::Ai21 => Color::Rgb(168, 85, 247),
            Self::Xai => Color::Rgb(0, 0, 0),
            Self::Stability => Color::Rgb(44, 151, 75),
            Self::Replicate => Color::Rgb(27, 27, 31),
            Self::HuggingFace => Color::Rgb(255, 210, 30),
            Self::Together => Color::Rgb(124, 58, 237),
            Self::Fireworks => Color::Rgb(255, 69, 0),
            Self::Groq => Color::Rgb(0, 178, 0),
            Self::DeepInfra => Color::Rgb(67, 56, 202),
            Self::Perplexity => Color::Rgb(255, 107, 53),
            Self::Sambanova => Color::Rgb(0, 128, 128),
            Self::Novita => Color::Rgb(37, 99, 235),
            Self::SiliconFlow => Color::Rgb(59, 130, 246),
            Self::Hyperbolic => Color::Rgb(124, 58, 237),
            Self::Lepton => Color::Rgb(139, 92, 246),
            Self::Featherless => Color::Rgb(139, 92, 246),
            Self::Nebius => Color::Rgb(37, 99, 235),
            Self::Korbit => Color::Rgb(0, 180, 216),
            Self::Writer => Color::Rgb(13, 148, 136),
            Self::Abacus => Color::Rgb(37, 99, 235),
            Self::Cerebras => Color::Rgb(37, 99, 235),
            Self::Alibaba => Color::Rgb(255, 106, 0),
            Self::Baidu => Color::Rgb(41, 50, 225),
            Self::Tencent => Color::Rgb(0, 82, 217),
            Self::ByteDance => Color::Rgb(255, 0, 0),
            Self::Zhipu => Color::Rgb(30, 144, 255),
            Self::Oneworld => Color::Rgb(37, 99, 235),
            Self::Moonshot => Color::Rgb(79, 107, 237),
            Self::Minimax => Color::Rgb(139, 92, 246),
            Self::Baichuan => Color::Rgb(37, 99, 235),
            Self::StepFun => Color::Rgb(59, 130, 246),
            Self::SenseTime => Color::Rgb(220, 38, 38),
            Self::Huawei => Color::Rgb(206, 17, 38),
            Self::Lingyiwanwu => Color::Rgb(37, 99, 235),
            Self::Infinigence => Color::Rgb(79, 107, 237),
            Self::Azure => Color::Rgb(0, 120, 212),
            Self::Aws => Color::Rgb(255, 153, 0),
            Self::Gcp => Color::Rgb(66, 133, 244),
            Self::Ibm => Color::Rgb(5, 74, 218),
            Self::Oracle => Color::Rgb(248, 0, 0),
            Self::Sap => Color::Rgb(0, 82, 217),
            Self::Nvidia => Color::Rgb(118, 185, 0),
            Self::Cloudflare => Color::Rgb(243, 128, 32),
            Self::OpenRouter => Color::Rgb(139, 92, 246),
            Self::Portkey => Color::Rgb(37, 99, 235),
            Self::Helicone => Color::Rgb(67, 56, 202),
            Self::LangChain => Color::Rgb(124, 58, 237),
            Self::LlamaIndex => Color::Rgb(255, 107, 53),
            Self::Vercel => Color::Rgb(0, 0, 0),
            Self::Modal => Color::Rgb(0, 0, 0),
            Self::Databricks => Color::Rgb(255, 54, 33),
            Self::Ollama => Color::Rgb(0, 180, 204),
            Self::LocalAI => Color::Rgb(59, 130, 246),
            Self::Vllm => Color::Rgb(37, 99, 235),
            Self::Tabby => Color::Rgb(255, 107, 53),
            Self::Gpt4All => Color::Rgb(79, 107, 237),
            Self::Pinecone => Color::Rgb(0, 180, 216),
            Self::Weaviate => Color::Rgb(0, 180, 216),
            Self::Chroma => Color::Rgb(255, 107, 53),
            Self::Milvus => Color::Rgb(0, 180, 216),
            Self::Qdrant => Color::Rgb(255, 69, 0),
            Self::Supabase => Color::Rgb(62, 207, 142),
            Self::MotherDuck => Color::Rgb(255, 107, 53),
            Self::Flyio => Color::Rgb(107, 33, 168),
            Self::Railway => Color::Rgb(124, 58, 237),
            Self::Render => Color::Rgb(70, 227, 183),
            Self::Scale => Color::Rgb(37, 99, 235),
            Self::Midjourney => Color::Rgb(0, 0, 0),
            Self::Runway => Color::Rgb(0, 0, 0),
            Self::Pika => Color::Rgb(255, 0, 128),
            Self::ElevenLabs => Color::Rgb(0, 0, 0),
            Self::Synthesia => Color::Rgb(0, 180, 216),
            Self::Goose => Color::Rgb(37, 99, 235),
            Self::Mosaicml => Color::Rgb(37, 99, 235),
        }
    }

    /// Returns a human-readable display name for this provider.
    pub fn name(self) -> &'static str {
        match self {
            Self::OpenAI => "OpenAI",
            Self::Anthropic => "Anthropic",
            Self::Google => "Google",
            Self::Meta => "Meta",
            Self::Mistral => "Mistral",
            Self::DeepSeek => "DeepSeek",
            Self::Cohere => "Cohere",
            Self::Ai21 => "AI21",
            Self::Xai => "xAI",
            Self::Stability => "Stability AI",
            Self::Replicate => "Replicate",
            Self::HuggingFace => "Hugging Face",
            Self::Together => "Together AI",
            Self::Fireworks => "Fireworks AI",
            Self::Groq => "Groq",
            Self::DeepInfra => "DeepInfra",
            Self::Perplexity => "Perplexity",
            Self::Sambanova => "SambaNova",
            Self::Novita => "Novita AI",
            Self::SiliconFlow => "SiliconFlow",
            Self::Hyperbolic => "Hyperbolic",
            Self::Lepton => "Lepton AI",
            Self::Featherless => "Featherless",
            Self::Nebius => "Nebius",
            Self::Korbit => "Korbit",
            Self::Writer => "Writer",
            Self::Abacus => "Abacus AI",
            Self::Cerebras => "Cerebras",
            Self::Alibaba => "Alibaba Cloud",
            Self::Baidu => "Baidu",
            Self::Tencent => "Tencent",
            Self::ByteDance => "ByteDance",
            Self::Zhipu => "Zhipu AI",
            Self::Oneworld => "01.AI",
            Self::Moonshot => "Moonshot AI",
            Self::Minimax => "MiniMax",
            Self::Baichuan => "Baichuan",
            Self::StepFun => "StepFun",
            Self::SenseTime => "SenseTime",
            Self::Huawei => "Huawei",
            Self::Lingyiwanwu => "Lingyiwanwu",
            Self::Infinigence => "Infinigence",
            Self::Azure => "Azure",
            Self::Aws => "AWS",
            Self::Gcp => "GCP",
            Self::Ibm => "IBM",
            Self::Oracle => "Oracle",
            Self::Sap => "SAP",
            Self::Nvidia => "NVIDIA",
            Self::Cloudflare => "Cloudflare",
            Self::OpenRouter => "OpenRouter",
            Self::Portkey => "Portkey",
            Self::Helicone => "Helicone",
            Self::LangChain => "LangChain",
            Self::LlamaIndex => "LlamaIndex",
            Self::Vercel => "Vercel",
            Self::Modal => "Modal",
            Self::Databricks => "Databricks",
            Self::Ollama => "Ollama",
            Self::LocalAI => "LocalAI",
            Self::Vllm => "vLLM",
            Self::Tabby => "Tabby",
            Self::Gpt4All => "GPT4All",
            Self::Pinecone => "Pinecone",
            Self::Weaviate => "Weaviate",
            Self::Chroma => "Chroma",
            Self::Milvus => "Milvus",
            Self::Qdrant => "Qdrant",
            Self::Supabase => "Supabase",
            Self::MotherDuck => "MotherDuck",
            Self::Flyio => "Fly.io",
            Self::Railway => "Railway",
            Self::Render => "Render",
            Self::Scale => "Scale AI",
            Self::Midjourney => "Midjourney",
            Self::Runway => "Runway",
            Self::Pika => "Pika",
            Self::ElevenLabs => "ElevenLabs",
            Self::Synthesia => "Synthesia",
            Self::Goose => "Goose AI",
            Self::Mosaicml => "MosaicML",
        }
    }

    /// Returns a static slice of every known provider.
    pub fn all() -> &'static [Provider] {
        static ALL: &[Provider] = &[
            Provider::OpenAI,
            Provider::Anthropic,
            Provider::Google,
            Provider::Meta,
            Provider::Mistral,
            Provider::DeepSeek,
            Provider::Cohere,
            Provider::Ai21,
            Provider::Xai,
            Provider::Stability,
            Provider::Replicate,
            Provider::HuggingFace,
            Provider::Together,
            Provider::Fireworks,
            Provider::Groq,
            Provider::DeepInfra,
            Provider::Perplexity,
            Provider::Sambanova,
            Provider::Novita,
            Provider::SiliconFlow,
            Provider::Hyperbolic,
            Provider::Lepton,
            Provider::Featherless,
            Provider::Nebius,
            Provider::Korbit,
            Provider::Writer,
            Provider::Abacus,
            Provider::Cerebras,
            Provider::Alibaba,
            Provider::Baidu,
            Provider::Tencent,
            Provider::ByteDance,
            Provider::Zhipu,
            Provider::Oneworld,
            Provider::Moonshot,
            Provider::Minimax,
            Provider::Baichuan,
            Provider::StepFun,
            Provider::SenseTime,
            Provider::Huawei,
            Provider::Lingyiwanwu,
            Provider::Infinigence,
            Provider::Azure,
            Provider::Aws,
            Provider::Gcp,
            Provider::Ibm,
            Provider::Oracle,
            Provider::Sap,
            Provider::Nvidia,
            Provider::Cloudflare,
            Provider::OpenRouter,
            Provider::Portkey,
            Provider::Helicone,
            Provider::LangChain,
            Provider::LlamaIndex,
            Provider::Vercel,
            Provider::Modal,
            Provider::Databricks,
            Provider::Ollama,
            Provider::LocalAI,
            Provider::Vllm,
            Provider::Tabby,
            Provider::Gpt4All,
            Provider::Pinecone,
            Provider::Weaviate,
            Provider::Chroma,
            Provider::Milvus,
            Provider::Qdrant,
            Provider::Supabase,
            Provider::MotherDuck,
            Provider::Flyio,
            Provider::Railway,
            Provider::Render,
            Provider::Scale,
            Provider::Midjourney,
            Provider::Runway,
            Provider::Pika,
            Provider::ElevenLabs,
            Provider::Synthesia,
            Provider::Goose,
            Provider::Mosaicml,
        ];
        ALL
    }

    /// Parses a provider name from a string (case-insensitive, handles
    /// common aliases like `"claude"` → `Anthropic`, `"gpt"` → `OpenAI`).
    #[allow(clippy::should_implement_trait)]
    pub fn from_str(s: &str) -> Option<Provider> {
        let lower = s.to_lowercase();
        match lower.as_str() {
            "openai" | "open_ai" | "gpt" => Some(Self::OpenAI),
            "anthropic" | "claude" => Some(Self::Anthropic),
            "google" | "gemini" => Some(Self::Google),
            "meta" | "llama" => Some(Self::Meta),
            "mistral" => Some(Self::Mistral),
            "deepseek" => Some(Self::DeepSeek),
            "cohere" | "command" => Some(Self::Cohere),
            "ai21" | "ai_21" => Some(Self::Ai21),
            "xai" | "x_ai" | "grok" => Some(Self::Xai),
            "stability" | "stability_ai" => Some(Self::Stability),
            "replicate" => Some(Self::Replicate),
            "huggingface" | "hugging_face" | "hf" => Some(Self::HuggingFace),
            "together" | "together_ai" => Some(Self::Together),
            "fireworks" | "fireworks_ai" => Some(Self::Fireworks),
            "groq" => Some(Self::Groq),
            "deepinfra" | "deep_infra" => Some(Self::DeepInfra),
            "perplexity" => Some(Self::Perplexity),
            "sambanova" | "samba_nova" => Some(Self::Sambanova),
            "novita" | "novita_ai" => Some(Self::Novita),
            "siliconflow" | "silicon_flow" => Some(Self::SiliconFlow),
            "hyperbolic" => Some(Self::Hyperbolic),
            "lepton" | "lepton_ai" => Some(Self::Lepton),
            "featherless" => Some(Self::Featherless),
            "nebius" => Some(Self::Nebius),
            "korbit" => Some(Self::Korbit),
            "writer" => Some(Self::Writer),
            "abacus" | "abacus_ai" => Some(Self::Abacus),
            "cerebras" => Some(Self::Cerebras),
            "alibaba" | "qwen" => Some(Self::Alibaba),
            "baidu" | "ernie" => Some(Self::Baidu),
            "tencent" | "hunyuan" => Some(Self::Tencent),
            "bytedance" | "byte_dance" | "doubao" => Some(Self::ByteDance),
            "zhipu" | "glm" => Some(Self::Zhipu),
            "01.ai" | "01_ai" | "yi" | "oneworld" => Some(Self::Oneworld),
            "moonshot" | "kimi" => Some(Self::Moonshot),
            "minimax" | "mini_max" => Some(Self::Minimax),
            "baichuan" => Some(Self::Baichuan),
            "stepfun" | "step" => Some(Self::StepFun),
            "sensetime" | "sense_time" => Some(Self::SenseTime),
            "huawei" | "pangu" => Some(Self::Huawei),
            "lingyiwanwu" => Some(Self::Lingyiwanwu),
            "infinigence" => Some(Self::Infinigence),
            "azure" | "azure_openai" => Some(Self::Azure),
            "aws" | "amazon" | "bedrock" => Some(Self::Aws),
            "gcp" | "vertex" | "google_cloud" => Some(Self::Gcp),
            "ibm" | "watsonx" | "watson" => Some(Self::Ibm),
            "oracle" | "oci" => Some(Self::Oracle),
            "sap" => Some(Self::Sap),
            "nvidia" | "nim" => Some(Self::Nvidia),
            "cloudflare" | "workers_ai" => Some(Self::Cloudflare),
            "openrouter" => Some(Self::OpenRouter),
            "portkey" => Some(Self::Portkey),
            "helicone" => Some(Self::Helicone),
            "langchain" | "lang_chain" => Some(Self::LangChain),
            "llamaindex" | "llama_index" => Some(Self::LlamaIndex),
            "vercel" | "ai_sdk" => Some(Self::Vercel),
            "modal" => Some(Self::Modal),
            "databricks" => Some(Self::Databricks),
            "ollama" => Some(Self::Ollama),
            "localai" | "local_ai" => Some(Self::LocalAI),
            "vllm" => Some(Self::Vllm),
            "tabby" => Some(Self::Tabby),
            "gpt4all" | "gpt4_all" => Some(Self::Gpt4All),
            "pinecone" => Some(Self::Pinecone),
            "weaviate" => Some(Self::Weaviate),
            "chroma" => Some(Self::Chroma),
            "milvus" => Some(Self::Milvus),
            "qdrant" => Some(Self::Qdrant),
            "supabase" => Some(Self::Supabase),
            "motherduck" | "mother_duck" => Some(Self::MotherDuck),
            "fly.io" | "flyio" | "fly_io" => Some(Self::Flyio),
            "railway" => Some(Self::Railway),
            "render" => Some(Self::Render),
            "scale" | "scale_ai" => Some(Self::Scale),
            "midjourney" => Some(Self::Midjourney),
            "runway" => Some(Self::Runway),
            "pika" => Some(Self::Pika),
            "elevenlabs" | "eleven_labs" => Some(Self::ElevenLabs),
            "synthesia" => Some(Self::Synthesia),
            "goose" | "goose_ai" => Some(Self::Goose),
            "mosaicml" | "mosaic_ml" => Some(Self::Mosaicml),
            _ => None,
        }
    }
}

/// Returns the brand colour for OpenAI.
pub fn openai() -> Color {
    Provider::OpenAI.color()
}
/// Returns the brand colour for Anthropic.
pub fn anthropic() -> Color {
    Provider::Anthropic.color()
}
/// Returns the brand colour for Google.
pub fn google() -> Color {
    Provider::Google.color()
}
/// Returns the brand colour for Meta.
pub fn meta() -> Color {
    Provider::Meta.color()
}
/// Returns the brand colour for Mistral.
pub fn mistral() -> Color {
    Provider::Mistral.color()
}
/// Returns the brand colour for DeepSeek.
pub fn deepseek() -> Color {
    Provider::DeepSeek.color()
}
/// Returns the brand colour for Cohere.
pub fn cohere() -> Color {
    Provider::Cohere.color()
}
/// Returns the brand colour for Ollama.
pub fn ollama() -> Color {
    Provider::Ollama.color()
}
